document.getElementById("swap").addEventListener("click", () => {

    let fromSelect = document.getElementById("fromselect");
    let toSelect = document.getElementById("toselect");

    let temp = fromSelect.value;
    fromSelect.value = toSelect.value;
    toSelect.value = temp;
});
document.querySelector("form").addEventListener("submit" , (event) => {
    event.preventDefault();
    clearerror();

    let from = document.getElementById("fromselect").value
    let to = document.getElementById("toselect").value
    let amount = document.getElementById("amount").value


    if(from === ""){
        document.getElementById("errorshowfrom").innerHTML = "Plase Select Country"
     
    } 
    if(to === ""){
        document.getElementById("errorshowto").innerHTML = "Plase Select Country"
        return
    } else{
        if(from === to){
            document.getElementById("errorshowto").innerHTML = "Do not Select Same Country"
            return;
        }
        if (amount == "" || amount <= 0) {
            document.getElementById("errorshowamount").innerHTML = "Enter Amout for Convert"
            return
        } 
    } 



let countryRates = {
  "AF": 0.95,
  "AL": 0.89,
  "DZ": 0.61,
  "AD": 90.3,
  "AO": 0.1,
  "AR": 0.096,
  "AM": 0.21,
  "AU": 55.9,
  "AT": 90.3,
  "AZ": 49.2,
  "BH": 221.0,
  "BD": 0.76,
  "BY": 25.0,
  "BE": 90.3,
  "BJ": 0.14,
  "BT": 1.0,
  "BO": 12.1,
  "BA": 45.2,
  "BW": 6.3,
  "BR": 15.0,
  "BN": 61.7,
  "BG": 45.8,
  "BF": 0.14,
  "BI": 0.029,
  "KH": 0.02,
  "CM": 0.14,
  "CA": 61.6,
  "CV": 0.82,
  "CF": 0.14,
  "TD": 0.14,
  "CL": 0.09,
  "CN": 11.5,
  "CO": 0.021,
  "KM": 0.18,
  "CG": 0.1,
  "CD": 0.044,
  "CR": 0.16,
  "HR": 90.3,
  "CU": 3.3,
  "CY": 90.3,
  "CZ": 3.5,
  "DK": 11.9,
  "DJ": 0.47,
  "DO": 1.42,
  "EC": 83.3,
  "EG": 1.73,
  "SV": 83.3,
  "GQ": 0.14,
  "EE": 90.3,
  "ET": 1.5,
  "FJ": 36.2,
  "FI": 90.3,
  "FR": 90.3,
  "GA": 0.14,
  "GM": 1.28,
  "GE": 31.2,
  "DE": 90.3,
  "GH": 6.9,
  "GR": 90.3,
  "GT": 1.07,
  "GN": 0.0094,
  "GY": 0.4,
  "HT": 0.62,
  "HN": 3.37,
  "HU": 0.23,
  "IS": 0.61,
  "IN": 1.0,
  "ID": 0.0051,
  "IR": 0.002,
  "IQ": 0.063,
  "IE": 90.3,
  "IL": 22.7,
  "IT": 90.3,
  "CI": 0.14,
  "JM": 0.54,
  "JP": 0.53,
  "JO": 117.5,
  "KZ": 0.19,
  "KE": 0.64,
  "KR": 0.06,
  "KW": 271.0,
  "KG": 0.94,
  "LA": 0.0039,
  "LV": 90.3,
  "LB": 0.0056,
  "LS": 4.3,
  "LR": 0.045,
  "LY": 17.0,
  "LT": 90.3,
  "LU": 90.3,
  "MG": 0.018,
  "MW": 0.049,
  "MY": 17.7,
  "MV": 5.4,
  "ML": 0.14,
  "MT": 90.3,
  "MR": 0.22,
  "MU": 1.87,
  "MX": 4.9,
  "MD": 4.7,
  "MN": 0.024,
  "ME": 90.3,
  "MA": 8.3,
  "MZ": 1.3,
  "MM": 0.04,
  "NA": 4.3,
  "NP": 0.63,
  "NL": 90.3,
  "NZ": 50.3,
  "NI": 2.3,
  "NE": 0.14,
  "NG": 0.056,
  "MK": 1.47,
  "NO": 7.3,
  "OM": 216.0,
  "PK": 0.3,
  "PA": 83.3,
  "PG": 23.2,
  "PY": 0.011,
  "PE": 22.5,
  "PH": 1.43,
  "PL": 21.0,
  "PT": 90.3,
  "QA": 22.9,
  "RO": 18.0,
  "RU": 0.96,
  "RW": 0.069,
  "SA": 22.2,
  "SN": 0.14,
  "RS": 0.77,
  "SG": 61.7,
  "SK": 90.3,
  "SI": 90.3,
  "ZA": 4.5,
  "ES": 90.3,
  "LK": 0.28,
  "SD": 0.071,
  "SE": 7.6,
  "CH": 95.6,
  "SY": 0.0064,
  "TW": 2.6,
  "TJ": 0.074,
  "TZ": 0.032,
  "TH": 2.3,
  "TL": 83.3,
  "TG": 0.14,
  "TN": 2.6,
  "TR": 2.5,
  "TM": 24.3,
  "UG": 0.022,
  "UA": 2.2,
  "AE": 22.7,
  "GB": 105.3,
  "US": 83.3,
  "UY": 2.1,
  "UZ": 0.0067,
  "VE": 0.029,
  "VN": 0.0033,
  "YE": 0.33,
  "ZM": 4.1,
  "ZW": 0.0074
};
let currencySymbols = {
  "AF": "؋ (Afghan Afghani)",
  "AL": "L (Albanian Lek)",
  "DZ": "دج (Algerian Dinar)",
  "AD": "€ (Euro)",
  "AO": "Kz (Angolan Kwanza)",
  "AR": "$ (Argentine Peso)",
  "AM": "֏ (Armenian Dram)",
  "AU": "$ (Australian Dollar)",
  "AT": "€ (Euro)",
  "AZ": "₼ (Azerbaijani Manat)",
  "BH": ".د.ب (Bahraini Dinar)",
  "BD": "৳ (Bangladeshi Taka)",
  "BY": "Br (Belarusian Ruble)",
  "BE": "€ (Euro)",
  "BJ": "CFA (West African CFA franc)",
  "BT": "Nu. (Bhutanese Ngultrum)",
  "BO": "Bs. (Bolivian Boliviano)",
  "BA": "KM (Bosnia Convertible Mark)",
  "BW": "P (Botswana Pula)",
  "BR": "R$ (Brazilian Real)",
  "BN": "$ (Brunei Dollar)",
  "BG": "лв (Bulgarian Lev)",
  "BF": "CFA (West African CFA franc)",
  "BI": "FBu (Burundian Franc)",
  "KH": "៛ (Cambodian Riel)",
  "CM": "CFA (Central African CFA franc)",
  "CA": "$ (Canadian Dollar)",
  "CV": "$ (Cape Verdean Escudo)",
  "CF": "CFA (Central African CFA franc)",
  "TD": "CFA (Central African CFA franc)",
  "CL": "$ (Chilean Peso)",
  "CN": "¥ (Chinese Yuan)",
  "CO": "$ (Colombian Peso)",
  "KM": "CF (Comorian Franc)",
  "CG": "CFA (Central African CFA franc)",
  "CD": "FC (Congolese Franc)",
  "CR": "₡ (Costa Rican Colón)",
  "HR": "€ (Euro)",
  "CU": "$ (Cuban Peso)",
  "CY": "€ (Euro)",
  "CZ": "Kč (Czech Koruna)",
  "DK": "kr (Danish Krone)",
  "DJ": "Fdj (Djiboutian Franc)",
  "DO": "RD$ (Dominican Peso)",
  "EC": "$ (US Dollar)",
  "EG": "£ (Egyptian Pound)",
  "SV": "$ (US Dollar)",
  "GQ": "CFA (Central African CFA franc)",
  "EE": "€ (Euro)",
  "ET": "Br (Ethiopian Birr)",
  "FJ": "$ (Fijian Dollar)",
  "FI": "€ (Euro)",
  "FR": "€ (Euro)",
  "GA": "CFA (Central African CFA franc)",
  "GM": "D (Gambian Dalasi)",
  "GE": "₾ (Georgian Lari)",
  "DE": "€ (Euro)",
  "GH": "₵ (Ghanaian Cedi)",
  "GR": "€ (Euro)",
  "GT": "Q (Guatemalan Quetzal)",
  "GN": "FG (Guinean Franc)",
  "GY": "$ (Guyanese Dollar)",
  "HT": "G (Haitian Gourde)",
  "HN": "L (Honduran Lempira)",
  "HU": "Ft (Hungarian Forint)",
  "IS": "kr (Icelandic Króna)",
  "IN": "₹ (Indian Rupee)",
  "ID": "Rp (Indonesian Rupiah)",
  "IR": "﷼ (Iranian Rial)",
  "IQ": "ع.د (Iraqi Dinar)",
  "IE": "€ (Euro)",
  "IL": "₪ (Israeli Shekel)",
  "IT": "€ (Euro)",
  "CI": "CFA (West African CFA franc)",
  "JM": "J$ (Jamaican Dollar)",
  "JP": "¥ (Japanese Yen)",
  "JO": "JD (Jordanian Dinar)",
  "KZ": "₸ (Kazakhstani Tenge)",
  "KE": "KSh (Kenyan Shilling)",
  "KR": "₩ (South Korean Won)",
  "KW": "KD (Kuwaiti Dinar)",
  "KG": "с (Kyrgyzstani Som)",
  "LA": "₭ (Lao Kip)",
  "LV": "€ (Euro)",
  "LB": "ل.ل (Lebanese Pound)",
  "LS": "L (Lesotho Loti)",
  "LR": "$ (Liberian Dollar)",
  "LY": "LD (Libyan Dinar)",
  "LT": "€ (Euro)",
  "LU": "€ (Euro)",
  "MG": "Ar (Malagasy Ariary)",
  "MW": "MK (Malawian Kwacha)",
  "MY": "RM (Malaysian Ringgit)",
  "MV": "Rf (Maldivian Rufiyaa)",
  "ML": "CFA (West African CFA franc)",
  "MT": "€ (Euro)",
  "MR": "UM (Mauritanian Ouguiya)",
  "MU": "₨ (Mauritian Rupee)",
  "MX": "$ (Mexican Peso)",
  "MD": "L (Moldovan Leu)",
  "MN": "₮ (Mongolian Tögrög)",
  "ME": "€ (Euro)",
  "MA": "د.م. (Moroccan Dirham)",
  "MZ": "MT (Mozambican Metical)",
  "MM": "K (Burmese Kyat)",
  "NA": "$ (Namibian Dollar)",
  "NP": "रू (Nepalese Rupee)",
  "NL": "€ (Euro)",
  "NZ": "$ (New Zealand Dollar)",
  "NI": "C$ (Nicaraguan Córdoba)",
  "NE": "CFA (West African CFA franc)",
  "NG": "₦ (Nigerian Naira)",
  "MK": "ден (Macedonian Denar)",
  "NO": "kr (Norwegian Krone)",
  "OM": "ر.ع. (Omani Rial)",
  "PK": "₨ (Pakistani Rupee)",
  "PA": "$ (US Dollar)",
  "PG": "K (Papua New Guinean Kina)",
  "PY": "₲ (Paraguayan Guaraní)",
  "PE": "S/ (Peruvian Sol)",
  "PH": "₱ (Philippine Peso)",
  "PL": "zł (Polish Zloty)",
  "PT": "€ (Euro)",
  "QA": "ر.ق (Qatari Riyal)",
  "RO": "lei (Romanian Leu)",
  "RU": "₽ (Russian Ruble)",
  "RW": "FRw (Rwandan Franc)",
  "SA": "﷼ (Saudi Riyal)",
  "SN": "CFA (West African CFA franc)",
  "RS": "дин (Serbian Dinar)",
  "SG": "$ (Singapore Dollar)",
  "SK": "€ (Euro)",
  "SI": "€ (Euro)",
  "ZA": "R (South African Rand)",
  "ES": "€ (Euro)",
  "LK": "Rs (Sri Lankan Rupee)",
  "SD": "£ (Sudanese Pound)",
  "SE": "kr (Swedish Krona)",
  "CH": "CHF (Swiss Franc)",
  "SY": "£ (Syrian Pound)",
  "TW": "NT$ (New Taiwan Dollar)",
  "TJ": "ЅМ (Tajikistani Somoni)",
  "TZ": "TSh (Tanzanian Shilling)",
  "TH": "฿ (Thai Baht)",
  "TL": "$ (US Dollar)",
  "TG": "CFA (West African CFA franc)",
  "TN": "د.ت (Tunisian Dinar)",
  "TR": "₺ (Turkish Lira)",
  "TM": "TMT (Turkmenistani Manat)",
  "UG": "USh (Ugandan Shilling)",
  "UA": "₴ (Ukrainian Hryvnia)",
  "AE": "د.إ (UAE Dirham)",
  "GB": "£ (British Pound)",
  "US": "$ (US Dollar)",
  "UY": "$U (Uruguayan Peso)",
  "UZ": "so'm (Uzbekistani So'm)",
  "VE": "Bs (Venezuelan Bolívar)",
  "VN": "₫ (Vietnamese Dong)",
  "YE": "﷼ (Yemeni Rial)",
  "ZM": "ZK (Zambian Kwacha)",
  "ZW": "$ (Zimbabwean Dollar)"
};


let fromrate = countryRates[from]
let torate = countryRates[to]
let convertedAmount = (amount * torate) / fromrate;
document.getElementById("result").innerHTML = ` ${amount}${currencySymbols[from]} =  ${convertedAmount.toFixed(2)} ${currencySymbols[to]}`

});

let clearerror = () => {
    document.querySelectorAll(".error").forEach(error => {
        error.innerHTML = "";
    });
};


